# Generated by Django 3.2.25 on 2024-05-20 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20240519_1359'),
        ('dealer', '0006_dealerbitcounts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerbitcounts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
