# Generated by Django 3.2.25 on 2024-05-21 07:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0007_alter_dealerbitcounts_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
